---
###############################################################
#                   Authelia configuration                    #
###############################################################

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
jwt_secret: b2538e33d1852cf043b789d8ed1a4d3fcaf172894affeff08d80b2a524397dcbba71226c63b725e42a000f0191553950fa4f4390d4c1068566bb981f1d3d7f20
default_redirection_url: https://auth.inator.dum-e.io

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

totp:
  issuer: auth.inator.dum-e.io
  period: 30
  skew: 1

duo_api:
  hostname: api-a1d2bf11.duosecurity.com
  integration_key: DIQV08J5SABSZ30PI8I3
  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
  secret_key: 1j6xsuUJlp5AbNgyy5SwpqJw1KmcRUsfvzfQGcrn

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 3
      salt_length: 16
      parallelism: 8
      memory: 1024 # blocks this much of the RAM. Tune this.

access_control:
  default_policy: one_factor
  rules:
    # Rules applied to everyone
    - domain:
        - "links.dum-e.io"
      policy: two_factor

session:
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  name: authelia_session
  domain: dum-e.io
  expiration: 1h
  inactivity: 30m
  remember_me_duration: 1M
  secret: 14b78d6a42c8971140608134bf6191f895b180c2feb6f7c36da4a93defd32b452724f4df09a34bc906d8bf29b51d6eb0de59375c38d05157b7184909d2403235

  redis:
    host: redis
    port: 6379
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: 091336adf1d1f53b682a44468fccf0479510ad720c5bd145f9236738d99c3c3df1ab7cc6a966ed427d9488d997c1f5beb1bcdca9ce503bfce7efd913af35892a
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username: rcnoetic@gmail.com
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    password: gfscoujfrdvswxvu
    host: smtp.gmail.com
    port: 587
    sender: admin@dum-e.io

identity_providers:
  oidc:
    hmac_secret: 59c8bb8c9db5cfe33efb5528591075ece723909f9dd62852522127076af987925d42511623c25a0288711cb09456fc1450da6de9e5b793663b86362873b56df5
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpgIBAAKCAQEAzuKe7nu/0K65+Qy1FEI7kdiB8OUFQgBfS3Ve71V0kCcAbvYX
      68wHRIJk0JhGmJpfJpzTTGw4PFDQkdLVhrVo9RSaiG6MqYEi4162EqfSHOobO2ZB
      57cN7+qDrpTWeg7z9FOwhakD2xtWKQlHKjYZzhX9iWO7bMlRRszXqdXyCAq2soQV
      MqJ1dHt0vBjoqJlMxo9F8jZAwbO+MZ7a8Sec7VCe31p6bPaR0taTwBKqrM00ZgJy
      oVL5/55yT9Niwr/JS0tUsZ5DTzkst1myxcggaBqDGsKuvaKrxZjUQX3bhkgsRi/r
      H84vRvKWNip5NorMh59U7vAOnHt7IaMKI+tnqwIDAQABAoIBAQCUBvqI0OqSOjK+
      zCTUdf+Bf1SaNIPqkbGdoEFpJc/dRMq+mj7LbJTWpCXWSt5YWjwyuItHZzdlkL1r
      WVuGo06R7UgUzmS+87Mu1JmaB5IDNk591dDaJtRGEZpe1AgSFZjf/PGU8TXdFFY1
      znmo7kTQfFOIdl+omvMYoYC9+GLQ9O+3iilg1AUJod6RkXfXaaWt9ApEfUatfGBA
      kuWR3+NVdcel8JPi8rSMY73i3I5Js3BbxiMVH/3gSg3WQCtcvRtGyN/q6cMxtuYD
      J4SznQkTm06BEbHVL+Me2CGLzEoyrkuImTJVK5uphTWsAaSW0QvpBrQknMx1DSXf
      TiNm3hEhAoGBAPJJakcDftH/JdIrEnmKmyg00shKq/svzVw/x3nhmVAuPSEGkgPt
      zvlfnWb30UPU7/dsiVZY1LzLU1uq2Zgf43uTkAgGsX2nJqQzJbsJ9yKVmk2LutnF
      KGY/ZqQHcReVOBBmcnddfOemKJCiGx0oy5VMuidTICHKpFz5gngl9aqVAoGBANqY
      QmVp6vtpEV7DsA8z0nCyWhyxhbZYV3gVKDWkzn7Ev27u8mF4SJg2/oHYurlgVq/H
      MJKlX2j8m7jwPQUnzd506IgnaSsYG9ZmNj1VkGocSY97rnqt0/TGwGQ41rqOo5Yw
      /jpQUMt56e4/1jrK9Y3eni2n8tvt5IKQDSnz/nk/AoGBALbUK3x26MYyUSntEr3g
      mACZC83Uez7K7Z6FClOwp25X1g0L1jdcxmhrfG1s597V2lbM8j3UPoRQshBkNlqT
      BagEzBUiZ+E3tvMFHZ2sgW75kTyfClq2aivt/9gbPX3cPjgx9oKYa16qhcXObcNt
      O2LoSTjPg1m8fpciOQ/NJTqZAoGBAJ7v5B7es1cXXuTbPdDf6hu84h5IySL6+qY6
      I+FVMjskDNi47g0GqynZmpWIosOUk5L9LokBquyn9wWxz3xHI72inUwZ87K8tcje
      yoMwCm/Mn4Ou9v8GEr3AITT9ysscWT8j4kU+DnDT9M4hJj/bQE1l1vb1TXSxdNul
      p5ygZp97AoGBALzIHZXYpm/xvuCsJvZMCGbUEXfEOkd10pC1a0Q6H7mPvscODIL1
      zQ7Sr5q8U4T3mLJ3j6XODVokwj6e9apzB/BH2wAurK1I2GIx5dMUm4GBdJwcP/m5
      mtABP+ekM63gwE3nGShCVPBJkF29iy6wqkwWf7etqlZjdQu+jKmyjPs1
      -----END RSA PRIVATE KEY-----
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
    clients:
      - id: portainer
        description: Portainer
        secret: '$argon2id$v=19$m=65536,t=3,p=4$Q2y+umXpjuPdo53M8Ubonw$SED4dkB5lq6KVXN4M7lAyi2KgC2Cu9wUEYuvxHpZi20'
        public: false
        authorization_policy: one_factor
        redirect_uris:
          - https://pods.inator.dum-e.io
        scopes:
          - openid
          - profile
          - groups
          - email
        userinfo_signing_algorithm: none
      - id: miniflux
        description: Miniflux
        secret: '$argon2id$v=19$m=65536,t=3,p=4$dRjrI1riXPi46XlKf3xjAw$RcYxngBI2d9ER+hm0LGx5gpbthdOdUxIkMzb3neem7k'
        public: false
        authorization_policy: one_factor
        redirect_uris:
          - https://feeds.dum-e.io/oauth2/oidc/callback
        scopes:
          - openid
          - profile
          - email
        userinfo_signing_algorithm: none
...
