services:
  kopia:
      image: kopia/kopia:latest
      container_name: Kopia
      user: "0:0"
      restart: "unless-stopped"
      privileged: true
      cap_add:
        - SYS_ADMIN
      security_opt:
        - apparmor:unconfined
      devices:
        - /dev/fuse:/dev/fuse:rwm
      networks:
        - proxy
      command:
        - server
        - start
        - --disable-csrf-token-checks
        - --insecure
        - --address=0.0.0.0:51515
        - --server-username=${KOPIA_USER}
        - --server-password=${KOPIA_PASSWORD}
      volumes:
        - /mnt/kopia:/tmp:shared
        - /home/tstark/pods/kopia/config:/app/config
        - /home/tstark/pods/kopia/cache:/app/cache
        - /home/tstark/pods/kopia/logs:/app/logs
        - /:/data:ro
      environment:
        - USER: ${KOPIA_USER}
        - TZ: ${TZ}
        - KOPIA_PASSWORD: 62135f6a28b1b834fc076f8f7fc0b162

networks:
  proxy:
    external: true
