services:
  miniflux:
    image: miniflux/miniflux:latest
    ports:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - OAUTH2_PROVIDER=oidc
      - OAUTH2_CLIENT_ID=miniflux
      - OAUTH2_CLIENT_SECRET=
      - OAUTH2_REDIRECT_URL=https://feed.dum-e.io/oauth2/callback
      - OAUTH2_OIDC_DISCOVERY_URL=https://auth.inator.dum-e.io/.well-known/openid-configuration
      - RUN_MIGRATIONS=1
    networks:
      - proxy
      - default
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
    volumes:
      - /home/tstark/pods/miniflux/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    networks:
      - default

networks:
  proxy:
    external: true
